### say hello
< scripts/traceparent.js

GET localhost:{{application-port}}/hello
Accept: application/json
# traceparent: {version}-{trace-id}-{span-id}-{trace-flags}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=hallo

### say hello2
< scripts/traceparent.js

GET localhost:{{application-port}}/hello2
Accept: application/json
# traceparent: {version}-{trace-id}-{span-id}-{trace-flags}
traceparent: 00-{{traceId}}-{{spanId}}-03
baggage: testBaggage=hallo
